boot:
  uploadPath: /var/uploaded_files/
  brokerAddress: 127.0.0.1:15555
  yanweiPath: http://api.yuntujk.net:9000/financial
  yanweiApiPath: http://api.yuntujk.net:9000
  yanweiApiVersion: 1.0.0
  appDomain: http://api.yuntujk.net:9000/wallet
  merchantTramsferFrontBackUrl: http://merchant.yuntujk.net:9000/#/m_finance/transfer-record
logging:
    level: 
        ROOT: INFO
    file: ./logs/wallet.log
spring:
   resources:
     static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,file:${boot.uploadPath}
   jpa:
     properties:
       hibernate:
         show_sql: true
         dialect: org.hibernate.dialect.MySQL5Dialect
         ejb:
           interceptor: com.yaozou.platform.common.interceptor.AutoUserTimeInterceptor
     hibernate:
       ddl-auto: none
       naming:
         strategy: org.hibernate.cfg.EJB3NamingStrategy
   datasource:
     type: com.alibaba.druid.pool.DruidDataSource
     driverClassName: com.mysql.jdbc.Driver
     url: jdbc:mysql://192.168.0.232:3306/yanwei_mall?useUnicode=true&characterEncoding=utf8&useSSL=true
     username: YanweiMall
     password: Yw2017
     initialSize: 1
     minIdle: 3
     maxActive: 20
     # 配置获取连接等待超时的时间  update
     maxWait: 60000
     # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
     timeBetweenEvictionRunsMillis: 60000
     # 配置一个连接在池中最小生存的时间，单位是毫秒
     minEvictableIdleTimeMillis: 30000
     validationQuery: select 'x'
     testWhileIdle: true
     testOnBorrow: false
     testOnReturn: false
     useSSL: false
     # 打开PSCache，并且指定每个连接上PSCache的大小
     poolPreparedStatements: true
     maxPoolPreparedStatementPerConnectionSize: 20
     # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
     filters: stat,wall,slf4j
     # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
     connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
     # 合并多个DruidDataSource的监控数据
     #useGlobalDataSourceStat: true
kafka:
  consumer:
    zookeeper:
      connect: 10.93.21.21:2181
    servers: 10.93.21.21:9092
    enable:
      auto:
        commit: true
    session:
      timeout: 6000
    auto:
      commit:
        interval: 100
      offset:
        reset: latest
    topic: test
    group:
      id: test
    concurrency: 10

  producer:
    servers: 10.93.21.21:9092
    retries: 0
    batch:
      size: 4096
    linger: 1
    buffer:
      memory: 40960

 