server:
  port: 7501
  maxHttpHeaderSize: 8192
  tomcat:
    max-connections: 2000
    max-threads: 2000
    min-spare-threads: 5
    uri-encoding: UTF-8
  context-path: /wallet
spring:
  thymeleaf:
    mode: LEGACYHTML5
    cache: false
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  profiles: 
    active: test
  http:
    multipart:
      max-file-size: 30Mb
      max-request-size: 30Mb
mybatis: 
  configuration:
    map-underscore-to-camel-case: true
  
